### ISSUE TITLE
How can I integrate this to logstash

### ISSUE THREAD

**Issue by maggiedot** [timfogarty1549/logstash-input-informatica#1]
Hello, I want to install your plugin into Logstash, I tried different versions of Logstash: `7.2`, `5.0` and `2.2` with this command:

```shell
./logstash --path.plugin  /opt/soft/logstash-input-informatica-master/lib
```

But none of them worked, could you introduce me how to integrate this into Logstash? 
Thanks~

**Comment by timfogarty1549** [comment]
That was so long ago and I haven’t used logstash since. I don’t know what changed have happened to logstash since. Nor do I know what changes have happened to informatica. But the documentation was very clear on how to create your own. You should be able to use mine as a starting point and create your own

**Comment by maggiedot** [comment]
@timfogarty1549 Thanks for your reply, the problem is fixed by manual build gem file and install.
